name: Maven Build

on:
  workflow_dispatch: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Clean
      uses: AutoModality/action-clean@v1
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.18.0
      with:
        java-version: 17
        java-distribution: adopt
        maven-version: 3.9.7
        settings-servers: |
          [{
            "id": "skyve",
            "username": "${{ secrets.NEXUSUSERNAME }}",
            "password": "${{ secrets.NEXUSPASSWORD }}"
          }]
    - name: Maven Build
      run: mvn -B clean compile skyve:generateDomain jacoco:prepare-agent test jacoco:report
    - name: Test Report
      uses: dorny/test-reporter@v2
      if: success() || failure()
      with:
        name: Test Report
        path: '**/target/surefire-reports/TEST-*.xml'
        reporter: java-junit
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
    - name: Reporting
      # if: github.event_name == 'pull_request'
      run: |
        echo "${{ github.type.type }} - test" >> $GITHUB_STEP_SUMMARY