name: Maven Build

on:
  workflow_dispatch: 
  push:
    branches: 
      - '*'

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Clean
      uses: AutoModality/action-clean@v1
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.18.0
      with:
        java-version: 17
        java-distribution: adopt
        maven-version: 3.9.7
      env:  
        registry-url: https://repo.skyve.org/repository/skyve-private/
        username: ${{ secrets.NEXUSUSERNAME }}
        password: ${{ secrets.NEXUSPASSWORD }}
    - name: Maven Build
      run: mvn -B clean compile skyve:generateDomain test --file pom.xml
    - name: Test Report
      uses: dorny/test-reporter@v2
      if: success() || failure()
      with:
        name: Test Report
        path: '**/target/surefire-reports/TEST-*.xml'
        reporter: java-junit
